- name: Loops topic
  hosts: localhost
  connection: local
  vars: 
   instance: 
    - a 
    - b
    - c
  tasks:
  - name: print variables in loop
    ansible.builtin.debug:
      msg: "{{ item }}"
    loop: "{{ instance }}"
    register: output
  
  - name: printing register
    ansible.builtin.debug:
      msg: " {{ output }}"