- name: Testing the loop
  hosts: local
  connection: local
  vars:
  instance:
  - mangodb
  - catalogue
  tags:
    Project: Testing
    Envi: Test
  
  tasks:
  - name: print the names
  loop: "{{ instance }}"
  name: "{{item}}"
  ansible.builtin.debug:
    msg: "{{ item }}"